{
	"APPLICATION_DATE": "${APPLICATION_DATE}",
	"APPLICATION_TYPE":"${APPLICATION_TYPE}",
	"FULL_NAME": "${FULL_NAME}",
	"TITLE": "${TITLE}",
	"FIRST_NAME": "${FIRST_NAME}",
	"MIDDLE_INITIAL": "${MIDDLE_INITIAL}",
	"LAST_NAME": "${LAST_NAME}",
	"SUFFIX": "${SUFFIX}",
	"ADDRESS_LINE1": "${ADDRESS_LINE1}",
	"ADDRESS_LINE2": "${ADDRESS_LINE2}",
	"ZIP": "${ZIP}",
	"ZIP4": "${ZIP4}",
	"CITY": "${CITY}",
	"STATE": "${STATE}",
	"BIRTH_DT": "${BIRTH_DT}"
}